---

- name: Check if prometheus pve user exist
  command: /usr/sbin/pveum user list
  register: pve_user_list
  check_mode: no

- name: Create prometheus pve user
  command: "/usr/sbin/pveum user add {{ proxmox_ve__spv_user }} -password {{ proxmox_ve__spv_password }}"
  when: proxmox_ve__spv_user not in pve_user_list.stdout

- name: Create prometheus pve user
  command: "/usr/sbin/pveum aclmod / -user {{ proxmox_ve__spv_user }} -role PVEAuditor"
  when: proxmox_ve__spv_user not in pve_user_list.stdout
