---
# handlers file for proxmox_ve


- name: update-grub
  command: update-grub

- name: Reboot Host
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: proxmox_ve__force_reboot

- name: restart iscsid
  service: name=iscsid state=restarted

- name: restart multipath
  service: name=multipath-tools state=restarted
